#!/usr/bin/env python3
"""Execute every copy-pasteable command in the prose, and refuse unrun claims.

`gen_article_blocks.py` regenerates blocks that claim to be *output*. It has a
blind spot: a block that claims to be an *input* — a command a reader will
copy — is never run, and neither is a block of output that simply forgot the
generator marker. Two pieces of fiction reached `main` through that gap:

  * `docs/quickstart.md` told readers to pipe `sbom-tools view -o json` into
    `cbomctl`. That projection carries no crypto fields at all, so the pipeline
    could never have produced a verdict. Nobody ran it.
  * `docs/index.md` — the docs-site landing page — carried a matrix with
    conflict ids that the tool does not emit for that input. Hand-edited, never
    generated, and it disagreed with the real output in four places.

So: every command block here is executed, or it is annotated as unverified with
a reason. Every block that looks like tool output is generated, or it is
annotated as illustrative with a reason. There is no third state in which
something merely looks checked.

Annotations go in an HTML comment immediately above the fence:

    <!-- cbomctl: verdict tests/fixtures/x.json -j bsi-de -->   generated output
    <!-- excerpt: verdict tests/fixtures/x.json -j bsi-de -->   a quote of that
    <!-- synopsis -->                       usage sketch; flags checked, not run
    <!-- unverified: <reason> -->           cannot run here, and why
    <!-- illustrative: <reason> -->         deliberately not real output

A single command line can be excused on its own with a trailing
`# unverified: <reason>`, so one clipboard write does not cost a block its
other checks.

Commands run against a scratch directory seeded with the placeholder filenames
the docs use (`app-cbom.json`, `cbomctl.yaml`, ...), so the documented line runs
verbatim, standing in for the reader's own CBOM.

Prose is checked too, not just fences: any `--flag` written anywhere in these
files must be one the CLI has, or must be listed in FOREIGN_FLAGS with the tool
it belongs to. Fences alone would have missed all three appearances of
`--strict-unknown`.

`pip install <name>` is resolved against the PyPI index — that is the whole of
what the line claims. Installing into a clean venv and running the console
script is a release step (`RELEASE.md`), not something to do on every commit;
when the index is unreachable the check reports SKIP rather than passing
quietly.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
FIXTURES = ROOT / "tests" / "fixtures"

#: Files whose prose makes claims a reader will act on. Listed rather than
#: rglob'd from ROOT so `.research/`, virtualenvs and vendored trees stay out.
SEARCH = [
    ROOT / "README.md",
    ROOT / "RELEASE.md",
    ROOT / "CONTRIBUTING.md",
    ROOT / "docs",
    ROOT / "articles",
    ROOT / "outreach",
    ROOT / "upstream",
    ROOT / "policy-packs" / "README.md",
    ROOT / ".github" / "ISSUE_TEMPLATE",
]

#: Byte-for-byte copies emitted by `gen_syndication.py`, which strips the
#: `<!-- cbomctl: -->` markers on the way out. Their source in `docs/writing/`
#: is swept here and generated by `gen_article_blocks.py`, and
#: `gen_syndication.py --check` pins the copies to it — so the chain is
#: complete, and re-checking the copies would only demand markers that the
#: generator deliberately removed.
GENERATED = {ROOT / "outreach" / "devto"}

SHELL_LANGS = {"bash", "sh", "shell", "console", "zsh"}

#: Flags in prose that belong to something else. Everything else written as
#: `--flag` anywhere in the swept prose must be a flag `cbomctl` actually has.
#:
#: `--strict-unknown` sat in `docs/DESIGN.md` for four releases — twice in a
#: table cell and once in a sentence, none of them in a fence. Checking only
#: fenced commands would have left all three. Each entry here names an owner,
#: because "that flag is somebody else's" is exactly the thing a reader can
#: get wrong too.
FOREIGN_FLAGS = {
    "--cbom": "open-quantum-secure",
    "--compliance": "open-quantum-secure",
    "--data-lifetime-years": "open-quantum-secure",
    "--sector": "open-quantum-secure",
    "--check": "our own scripts/gen_*.py and scripts/check_commands.py",
    "--infer-from-evidence": "unbuilt; docs/roadmap.md proposes it as future work",
}

#: Placeholder filename in the docs -> fixture that stands in for it.
PLACEHOLDERS = {
    "app-cbom.json": "conflict-hybrid.json",
    "app-cbom.cdx.json": "conflict-hybrid.json",
    "your-cbom.json": "conflict-hybrid.json",
    "cbom.json": "conflict-hybrid.json",
    "normalized.json": "sbom-tools-normalized.json",
}

FENCE = re.compile(r"^(?P<ind>[ \t]*)```(?P<lang>[A-Za-z0-9_+-]*)(?P<info>[^`]*)$")
COMMENT = re.compile(r"<!--(?P<body>.*?)-->", re.S)

_pypi_cache: dict[str, str] = {}


def shown(path: Path) -> Path:
    """Repo-relative when we can, absolute for a scratch doc under test."""
    try:
        return path.relative_to(ROOT)
    except ValueError:
        return path


class Block:
    def __init__(self, path: Path, line: int, lang: str, body: list[str], note: str):
        self.path, self.line, self.lang, self.body = path, line, lang, body
        self.note = " ".join(note.split())

    @property
    def where(self) -> str:
        return f"{shown(self.path)}:{self.line}"

    def annotation(self, kind: str) -> str | None:
        """The reason attached to `<!-- kind: reason -->`, or "" for a bare tag."""
        m = re.match(rf"{kind}\s*:\s*(.*)$", self.note, re.S)
        if m:
            return m.group(1).strip()
        return "" if self.note.strip() == kind else None


def blocks(path: Path):
    lines = path.read_text().split("\n")
    i = 0
    while i < len(lines):
        m = FENCE.match(lines[i])
        if not m:
            i += 1
            continue
        start, body = i + 1, []
        j = i + 1
        while j < len(lines) and not re.match(r"^[ \t]*```\s*$", lines[j]):
            body.append(lines[j])
            j += 1
        # The annotation is the HTML comment ending on the line above the fence.
        note = ""
        k = i - 1
        if k >= 0 and lines[k].rstrip().endswith("-->"):
            while k >= 0 and "<!--" not in lines[k]:
                k -= 1
            if k >= 0:
                cm = COMMENT.search("\n".join(lines[k:i]))
                if cm:
                    note = cm.group("body")
        yield Block(path, start, m.group("lang").lower(), body, note)
        i = j + 1


def scratch() -> Path:
    """A directory where the docs' placeholder filenames are real CBOMs."""
    d = Path(tempfile.mkdtemp(prefix="cbomctl-docs-"))
    for name, fixture in PLACEHOLDERS.items():
        shutil.copy(FIXTURES / fixture, d / name)
    shutil.copy(ROOT / "cbomctl.yaml.example", d / "cbomctl.yaml")
    shutil.copy(ROOT / "cbomctl.yaml.example", d / "cbomctl.yaml.example")
    (d / "tests").symlink_to(ROOT / "tests")
    return d


def run_cbomctl(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "cbomctl.cli", *args],
        capture_output=True, text=True, cwd=cwd,
        env={**os.environ, "PYTHONPATH": str(SRC), "NO_COLOR": "1",
             "TERM": "dumb", "COLUMNS": "100"},
    )


def pypi_has(name: str) -> str:
    """PASS / FAIL / SKIP for `pip install <name>` resolving on the index."""
    if name in _pypi_cache:
        return _pypi_cache[name]
    url = f"https://pypi.org/pypi/{name}/json"
    try:
        with urllib.request.urlopen(url, timeout=10) as fh:
            json.load(fh)
        verdict = "PASS"
    except urllib.error.HTTPError as exc:
        verdict = "FAIL" if exc.code == 404 else "SKIP"
    except Exception:
        # A python.org build with no CA bundle cannot verify pypi.org, and that
        # is a fact about this laptop, not about the package. Ask curl before
        # reporting the claim unchecked.
        code = subprocess.run(
            ["curl", "-sS", "-o", os.devnull, "-w", "%{http_code}", "--max-time", "15", url],
            capture_output=True, text=True).stdout.strip()
        verdict = {"200": "PASS", "404": "FAIL"}.get(code, "SKIP")
    _pypi_cache[name] = verdict
    return verdict


def all_commands(body: list[str]) -> bool:
    """True for an untagged fence that is only commands, not a transcript.

    A block that opens `$ cbomctl verdict ...` and then shows the matrix is a
    transcript: its command half is not what needs checking, its output half
    is. Those go to `check_output` and must be generated.
    """
    lines = [l.strip() for l in body if l.strip()]
    return bool(lines) and all(
        l.lstrip("$ ").startswith("cbomctl ") or l.startswith("#") for l in lines)


def check_repo_local(line: str) -> tuple[str | None, str]:
    """Resolve commands that point at this repo, without running them.

    `./scripts/check.sh` invokes this file, so executing it here would recurse.
    What is checkable without running is whether the thing named exists — which
    is the failure mode that actually happens: a script renamed, an extra
    dropped from `pyproject.toml`, a path in a `cat` that moved.
    """
    m = re.match(r"^(?:\./)?(scripts/[\w.-]+)(?:\s.*)?$", line)
    if not m:
        m = re.match(r"^python3?\s+(scripts/[\w.-]+)(?:\s.*)?$", line)
    if m:
        target = ROOT / m.group(1)
        if not target.exists():
            return "FAIL", f"{m.group(1)} does not exist"
        if line.startswith("./") and not os.access(target, os.X_OK):
            return "FAIL", f"{m.group(1)} is not executable"
        return "CHECKED", f"{m.group(1)} exists"

    m = re.match(r"^pip3? install -e ['\"]?\.\[(\w+)\]['\"]?$", line)
    if m:
        extras = (ROOT / "pyproject.toml").read_text()
        block = extras.split("[project.optional-dependencies]", 1)
        if len(block) < 2 or not re.search(rf"^{m.group(1)}\s*=", block[1], re.M):
            return "FAIL", f"pyproject declares no `{m.group(1)}` extra"
        return "CHECKED", f"`{m.group(1)}` extra is declared in pyproject.toml"

    if re.match(r"^pytest(\s|$)", line):
        deps = (ROOT / "pyproject.toml").read_text()
        return ("CHECKED", "pytest is a declared test dependency") if "pytest" in deps \
            else ("FAIL", "pytest is not a declared dependency")

    m = re.match(r"^cat\s+([\w./-]+)$", line)
    if m:
        target = ROOT / m.group(1)
        return ("CHECKED", f"{m.group(1)} exists") if target.exists() \
            else ("FAIL", f"{m.group(1)} does not exist")

    return None, ""


def check_shell(b: Block, cwd: Path, report: list) -> bool:
    reason = b.annotation("unverified")
    if reason is not None:
        if not reason:
            report.append(("FAIL", b.where, "`unverified` with no reason given"))
            return False
        report.append(("SKIP", b.where, f"unverified — {reason}"))
        return True

    ok = True
    for raw in b.body:
        line = raw.strip().lstrip("$ ").strip()
        trailing = re.search(r"\s+#\s*(.*)$", line)
        line = re.sub(r"\s+#.*$", "", line)          # trailing prose comment
        if not line or line.startswith("#"):
            continue

        # One unrunnable line should not cost a block its other checks, so the
        # annotation is available per line as well: `cmd  # unverified: why`.
        if trailing and trailing.group(1).startswith("unverified:"):
            why = trailing.group(1)[len("unverified:"):].strip()
            if not why:
                report.append(("FAIL", b.where,
                               f"`{line}` — `unverified` with no reason given"))
                ok = False
            else:
                report.append(("SKIP", b.where, f"`{line}` — unverified: {why}"))
            continue

        if re.match(r"^(pip|pip3|python3? -m pip) install ([A-Za-z0-9._-]+)$", line):
            name = line.split()[-1]
            verdict = pypi_has(name)
            report.append((verdict, b.where,
                           f"`{line}` — {name} on PyPI"
                           if verdict != "SKIP" else
                           f"`{line}` — index unreachable, not verified"))
            ok &= verdict != "FAIL"
            continue

        if not line.startswith("cbomctl "):
            verdict, detail = check_repo_local(line)
            if verdict is None:
                report.append(("FAIL", b.where, (
                    f"`{line}` is not a cbomctl invocation and the block carries "
                    f"no `<!-- unverified: reason -->`")))
                ok = False
            else:
                report.append((verdict, b.where, f"`{line}` — {detail}"))
                ok &= verdict != "FAIL"
            continue

        if re.search(r"[|;&><`]|\$\(", line):
            report.append(("FAIL", b.where,
                           f"`{line}` uses shell plumbing; run it or annotate it"))
            ok = False
            continue

        proc = run_cbomctl(shlex.split(line)[1:], cwd)
        blew_up = proc.returncode == 2 or "No such command" in proc.stderr
        report.append(("FAIL" if blew_up else "RAN", b.where,
                       f"`{line}` → exit {proc.returncode}"
                       + (f"\n        {proc.stderr.strip().splitlines()[0]}"
                          if blew_up and proc.stderr.strip() else "")))
        ok &= not blew_up
    return ok


def check_synopsis(b: Block, cwd: Path, report: list) -> bool:
    """A usage sketch is not runnable, but its flags must be real."""
    ok = True
    for raw in b.body:
        line = raw.strip()
        if not line:
            continue
        sub = None
        if line.startswith("cbomctl "):
            rest = line[len("cbomctl "):].split()
            sub = rest[0] if rest and not rest[0].startswith("-") else None
        if sub:
            proc = run_cbomctl([sub, "--help"], cwd)
            if proc.returncode != 0:
                report.append(("FAIL", b.where, f"no such subcommand: `{sub}`"))
                ok = False
                continue
            b._help = proc.stdout                                # noqa: SLF001
        help_text = getattr(b, "_help", "")
        for flag in re.findall(r"(?<![\w-])--[a-z][a-z0-9-]*", line):
            if help_text and flag not in help_text:
                report.append(("FAIL", b.where,
                               f"`{flag}` is not a flag the CLI has"))
                ok = False
    if ok:
        report.append(("CHECKED", b.where, "synopsis — subcommands and flags exist"))
    return ok


def check_prose_flags(path: Path, cwd: Path, report: list, help_text: str) -> bool:
    """Every `--flag` written in prose must be one the CLI has, or be foreign.

    Fenced commands are only half the claims a page makes. The other half is
    sentences and reference tables, and that is where `--strict-unknown`
    survived four releases.
    """
    ok = True
    for m in re.finditer(r"`(--[a-z][a-z0-9-]*)", path.read_text()):
        flag = m.group(1)
        if flag in FOREIGN_FLAGS or flag in help_text:
            continue
        line = path.read_text()[:m.start()].count("\n") + 1
        report.append(("FAIL", f"{shown(path)}:{line}", (
            f"`{flag}` is not a flag cbomctl has. If it belongs to another "
            f"tool or is future work, add it to FOREIGN_FLAGS with its owner")))
        ok = False
    return ok


def cli_help(cwd: Path) -> str:
    """Every subcommand's --help, concatenated, at a width that never wraps."""
    text = run_cbomctl(["--help"], cwd).stdout
    for sub in ("verdict", "prioritize", "plan", "normalize", "policies"):
        proc = subprocess.run(
            [sys.executable, "-m", "cbomctl.cli", sub, "--help"],
            capture_output=True, text=True, cwd=cwd,
            env={**os.environ, "PYTHONPATH": str(SRC), "NO_COLOR": "1",
                 "TERM": "dumb", "COLUMNS": "200"})
        text += proc.stdout
    return text


def check_output(b: Block, cwd: Path, report: list) -> bool:
    """An untagged fence in prose has to say what it is.

    Heuristics were tried first — look for `└ `, for `CONFLICTS (`, for a
    matrix header — and every one of them missed something. The fiction on the
    docs-site landing page had a bare `CONFLICTS` with no count; the block in
    `purpose.md` was a paraphrase with no tell at all. A fence either declares
    itself or it fails; there are few enough of them for that to be cheap.
    """
    if b.annotation("cbomctl") is not None:
        return True                       # gen_article_blocks.py owns this one

    cmd = b.annotation("excerpt")
    if cmd is not None:
        # Prose that quotes a few lines of output, rewrapped to the narrower
        # column the prose uses. `illustrative` would excuse it; this pins it
        # to the command instead, and checks against that command's *whole*
        # output — the quote is often a line the pasted block truncates away.
        if not cmd:
            report.append(("FAIL", b.where,
                           "`excerpt` needs the command it quotes: "
                           "`<!-- excerpt: verdict ... -->`"))
            return False
        args = shlex.split(cmd)
        proc = run_cbomctl(args[1:] if args[:1] == ["cbomctl"] else args, cwd)
        quoted = " ".join(" ".join(b.body).split())
        if quoted and quoted in " ".join(proc.stdout.split()):
            report.append(("CHECKED", b.where,
                           f"excerpt — found verbatim in `cbomctl {cmd}` output"))
            return True
        report.append(("FAIL", b.where, (
            f"marked `excerpt` of `cbomctl {cmd}`, but that command's output "
            f"does not contain it")))
        return False

    for kind in ("illustrative", "unverified"):
        reason = b.annotation(kind)
        if reason:
            report.append(("SKIP", b.where, f"{kind} — {reason}"))
            return True
        if reason == "":
            report.append(("FAIL", b.where, f"`{kind}` with no reason given"))
            return False
    report.append(("FAIL", b.where, (
        "untagged fence — if it is tool output give it a `<!-- cbomctl: ... -->` "
        "marker so it is generated; if it is a usage sketch mark it "
        "`<!-- synopsis -->`; otherwise `<!-- illustrative: reason -->`")))
    return False


#: Actions in the docs whose `action.yml` is fetched from their own repository
#: at the ref the snippet names, so `with:` keys are checked against what the
#: action really declares. `docs/ci.md` used to pass `with: { output: cbom.json }`
#: to CBOMkit's action, which declares no inputs at all; that half of the page
#: was corrected by hand and then went back to being unchecked. Fetching is the
#: only way to check somebody else's action, and it is why an entry here is
#: SKIPped rather than failed when the network is unreachable.
#:
#: An action *not* listed here is reported unchecked with its name, so adding
#: one to a snippet is a visible decision rather than a silent hole.
THIRD_PARTY_ACTIONS = {
    "actions/checkout",
    "actions/upload-artifact",
    "cbomkit/cbomkit-action",
    "github/codeql-action/upload-sarif",
}

#: Docker actions take no `with:` inputs; they are configured by environment
#: variables, which `action.yml` does not declare. What can still be checked is
#: that the name we tell a reader to set is one the action documents. Value:
#: the path in the action's repo that documents them.
ACTION_ENV_DOCS = {
    "cbomkit/cbomkit-action": "README.md",
}

_action_cache: dict[str, str | None] = {}


def fetch_raw(repo: str, ref: str, path: str) -> str | None:
    """A file from a GitHub repo at a ref, or None if it cannot be reached."""
    key = f"{repo}@{ref}/{path}"
    if key in _action_cache:
        return _action_cache[key]
    url = f"https://raw.githubusercontent.com/{repo}/{ref}/{path}"
    text: str | None = None
    try:
        with urllib.request.urlopen(url, timeout=15) as fh:
            text = fh.read().decode()
    except urllib.error.HTTPError as exc:
        text = "" if exc.code == 404 else None
    except Exception:
        # Same laptop-versus-package distinction `pypi_has` makes: a python.org
        # build with no CA bundle cannot verify github.com, and that is a fact
        # about this machine.
        proc = subprocess.run(
            ["curl", "-sS", "--max-time", "20", "-w", "\n%{http_code}", url],
            capture_output=True, text=True)
        body, _, code = proc.stdout.rpartition("\n")
        text = body if code.strip() == "200" else ("" if code.strip() == "404"
                                                   else None)
    _action_cache[key] = text
    return text


def declared_inputs(action_yml: str) -> set[str]:
    """Input names in an `action.yml`. Empty for an action declaring none."""
    try:
        import yaml
        doc = yaml.safe_load(action_yml) or {}
        return set((doc.get("inputs") or {}).keys())
    except Exception:
        return set()


def check_workflow(b: Block, report: list) -> bool:
    """Every action a CI snippet names must take the inputs the snippet passes.

    Both halves, not just ours. The half this file could not reach was named on
    the page as transcribed-not-run, and that annotation was doing the work a
    check should have been doing: their `action.yml` is a file, it is fetchable,
    and reading it is the whole of what "read against their action.yml" meant.
    """
    ok = True
    seen = False
    for line in b.body:
        m = re.search(r"uses:\s*([A-Za-z0-9._/-]+)@(\S+)", line)
        if not m:
            continue
        seen = True
        repo_path, ref = m.group(1), m.group(2)
        if repo_path == "lvlrSajjad/cbomctl":
            ok &= check_our_action(b, ref, report)
        else:
            ok &= check_third_party_action(b, repo_path, ref, report)
    if not seen:
        return True
    return ok


def check_our_action(b: Block, ref: str, report: list) -> bool:
    declared = declared_inputs((ROOT / "action.yml").read_text())
    ok = True
    known = subprocess.run(["git", "tag"], capture_output=True, text=True,
                           cwd=ROOT).stdout.split()
    if not known:
        # A shallow checkout has no tags. Saying nothing here would let the
        # check pass by accident, which is the failure this file exists to stop.
        report.append(("SKIP", b.where,
                       f"`@{ref}` unresolved — no tags in this checkout "
                       f"(fetch-depth: 0 is needed to verify it)"))
    elif ref not in known:
        report.append(("FAIL", b.where, f"`@{ref}` is not a tag in this repo"))
        ok = False

    used = mapping_keys(b.body, f"lvlrSajjad/cbomctl@{ref}", "with")
    for key in used:
        if key not in declared:
            report.append(("FAIL", b.where, f"`with: {key}` is not an action input"))
            ok = False
    if ok:
        report.append(("CHECKED", b.where,
                       f"action `@{ref}` exists; inputs {sorted(used)} declared"))
    return ok


def check_third_party_action(b: Block, repo_path: str, ref: str,
                             report: list) -> bool:
    used = mapping_keys(b.body, f"{repo_path}@{ref}", "with")
    env = mapping_keys(b.body, f"{repo_path}@{ref}", "env")

    if repo_path not in THIRD_PARTY_ACTIONS:
        report.append(("SKIP", b.where, (
            f"`{repo_path}@{ref}` is not resolved — add it to "
            f"THIRD_PARTY_ACTIONS to check the inputs this page passes it")))
        return True

    repo = "/".join(repo_path.split("/")[:2])
    subdir = "/".join(repo_path.split("/")[2:])
    prefix = f"{subdir}/" if subdir else ""
    action_yml = fetch_raw(repo, ref, f"{prefix}action.yml")
    if action_yml == "":
        action_yml = fetch_raw(repo, ref, f"{prefix}action.yaml")
    if action_yml is None:
        report.append(("SKIP", b.where, (
            f"`{repo_path}@{ref}` — github.com unreachable, inputs "
            f"{sorted(used)} not verified")))
        return True
    if action_yml == "":
        report.append(("FAIL", b.where, (
            f"`{repo_path}@{ref}` has no action.yml — the ref is wrong, or the "
            f"action moved")))
        return False

    ok = True
    declared = declared_inputs(action_yml)
    for key in used:
        if key not in declared:
            report.append(("FAIL", b.where, (
                f"`with: {key}` is not an input of `{repo_path}@{ref}`"
                + (f"; it declares none at all" if not declared else
                   f"; it declares {sorted(declared)}"))))
            ok = False

    if env:
        doc_path = ACTION_ENV_DOCS.get(repo_path)
        docs = fetch_raw(repo, ref, doc_path) if doc_path else None
        if not doc_path:
            report.append(("SKIP", b.where, (
                f"`env:` {sorted(env)} on `{repo_path}@{ref}` — nothing in the "
                f"action declares environment variables; add the file that "
                f"documents them to ACTION_ENV_DOCS to check the names")))
        elif docs is None:
            report.append(("SKIP", b.where, (
                f"`env:` {sorted(env)} — {repo}/{doc_path} unreachable")))
        else:
            for key in env:
                # Whole-word: `CBOMKIT_LANGUAGE` is a substring of the real
                # `CBOMKIT_LANGUAGES`, and a substring match would pass it.
                if not re.search(rf"\b{re.escape(key)}\b", docs):
                    report.append(("FAIL", b.where, (
                        f"`env: {key}` is not documented in "
                        f"{repo}/{doc_path} at `{ref}`")))
                    ok = False
    if ok:
        report.append(("CHECKED", b.where, (
            f"`{repo_path}@{ref}` — with {sorted(used)} declared, env "
            f"{sorted(env)} documented" if (used or env) else
            f"`{repo_path}@{ref}` resolves and is passed nothing")))
    return ok


def mapping_keys(body: list[str], uses: str, block: str) -> list[str]:
    """Keys of the `with:` (or `env:`) mapping on the step that `uses` this."""
    keys: list[str] = []
    for i, line in enumerate(body):
        if uses not in line:
            continue
        step_indent = len(line) - len(line.lstrip())
        inside = False
        for rest in body[i + 1:]:
            if not rest.strip():
                continue
            indent = len(rest) - len(rest.lstrip())
            if indent <= step_indent and rest.lstrip().startswith("- "):
                break                                   # next step
            m = re.match(rf"^\s*{block}:\s*\{{(.*)\}}\s*$", rest)
            if m:                                       # inline `with: { a: b }`
                keys += re.findall(r"([\w-]+)\s*:", m.group(1))
                continue
            if re.match(rf"^\s*{block}:\s*$", rest):
                inside = True
                continue
            if re.match(r"^\s*[\w-]+:\s*$", rest) and indent <= step_indent + 2:
                inside = False                          # a sibling of `with:`
            if inside and indent > step_indent + 2:
                m = re.match(r"^\s*([\w-]+):", rest)
                if m:
                    keys.append(m.group(1))
        break
    return sorted(set(keys))


def check_block(b: Block, cwd: Path, report: list) -> bool:
    """Route one fence to the check its annotation and language call for.

    One function, so `tests/test_check_commands.py` exercises the same routing
    the script does. Duplicating this in the tests would let the thing that
    proves the checker works drift from the checker.
    """
    if b.annotation("illustrative") is not None:
        # Deliberately not a real thing, whatever it looks like — a layout
        # drawing, or a blank for a bug reporter to fill in.
        return check_output(b, cwd, report)
    if b.annotation("synopsis") is not None:
        return check_synopsis(b, cwd, report)
    if b.lang in SHELL_LANGS or (not b.lang and all_commands(b.body)):
        return check_shell(b, cwd, report)
    if b.lang in ("", "text"):
        return check_output(b, cwd, report)
    if b.lang in ("yaml", "yml"):
        return check_workflow(b, report)
    reason = b.annotation("unverified")
    if reason is not None:
        if not reason:
            report.append(("FAIL", b.where, "`unverified` with no reason given"))
            return False
        report.append(("SKIP", b.where, f"unverified — {reason}"))
    return True


def main() -> int:
    check = "--check" in sys.argv
    cwd = scratch()
    report: list[tuple[str, str, str]] = []
    ok = True
    try:
        paths: list[Path] = []
        for base in SEARCH:
            paths += [base] if base.is_file() else sorted(base.rglob("*.md"))
        help_text = cli_help(cwd)
        for path in paths:
            if any(g in path.parents for g in GENERATED):
                continue
            ok &= check_prose_flags(path, cwd, report, help_text)
            for b in blocks(path):
                ok &= check_block(b, cwd, report)
    finally:
        shutil.rmtree(cwd, ignore_errors=True)

    width = max((len(w) for _, w, _ in report), default=0)
    for verdict, where, detail in report:
        print(f"  {verdict:<8} {where:<{width}}  {detail}")

    tally = {v: sum(1 for x, _, _ in report if x == v) for v in
             ("RAN", "PASS", "CHECKED", "SKIP", "FAIL")}
    print(f"\n  {tally['RAN']} commands executed, {tally['PASS']} resolved on PyPI, "
          f"{tally['CHECKED']} statically checked, {tally['SKIP']} marked unverified, "
          f"{tally['FAIL']} failing")
    if not ok:
        print("\nA command presented as working must have been run. If it cannot "
              "be run here,\nsay so above the fence: <!-- unverified: reason -->")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
