#!/usr/bin/env python3
"""Execute every copy-pasteable command in the prose, and refuse unrun claims.

`gen_article_blocks.py` regenerates blocks that claim to be *output*. It has a
blind spot: a block that claims to be an *input* — a command a reader will
copy — is never run, and neither is a block of output that simply forgot the
generator marker. Two pieces of fiction reached `main` through that gap:

  * `docs/quickstart.md` told readers to pipe `sbom-tools view -o json` into
    `cbomctl`. That projection carries no crypto fields at all, so the pipeline
    could never have produced a verdict. Nobody ran it.
  * `docs/index.md` — the docs-site landing page — carried a matrix with
    conflict ids that the tool does not emit for that input. Hand-edited, never
    generated, and it disagreed with the real output in four places.

So: every command block here is executed, or it is annotated as unverified with
a reason. Every block that looks like tool output is generated, or it is
annotated as illustrative with a reason. There is no third state in which
something merely looks checked.

Annotations go in an HTML comment immediately above the fence:

    <!-- cbomctl: verdict tests/fixtures/x.json -j bsi-de -->   generated output
    <!-- excerpt: verdict tests/fixtures/x.json -j bsi-de -->   a quote of that
    <!-- synopsis -->                       usage sketch; flags checked, not run
    <!-- unverified: <reason> -->           cannot run here, and why
    <!-- illustrative: <reason> -->         deliberately not real output

A single command line can be excused on its own with a trailing
`# unverified: <reason>`, so one clipboard write does not cost a block its
other checks.

Commands run against a scratch directory seeded with the placeholder filenames
the docs use (`app-cbom.json`, `cbomctl.yaml`, ...), so the documented line runs
verbatim, standing in for the reader's own CBOM.

`pip install <name>` is resolved against the PyPI index — that is the whole of
what the line claims. Installing into a clean venv and running the console
script is a release step (`RELEASE.md`), not something to do on every commit;
when the index is unreachable the check reports SKIP rather than passing
quietly.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
FIXTURES = ROOT / "tests" / "fixtures"

#: Files whose prose makes claims a reader will act on. Listed rather than
#: rglob'd from ROOT so `.research/`, virtualenvs and vendored trees stay out.
SEARCH = [
    ROOT / "README.md",
    ROOT / "RELEASE.md",
    ROOT / "CONTRIBUTING.md",
    ROOT / "docs",
    ROOT / "articles",
    ROOT / "outreach",
    ROOT / "upstream",
    ROOT / "policy-packs" / "README.md",
]

#: Byte-for-byte copies emitted by `gen_syndication.py`, which strips the
#: `<!-- cbomctl: -->` markers on the way out. Their source in `docs/writing/`
#: is swept here and generated by `gen_article_blocks.py`, and
#: `gen_syndication.py --check` pins the copies to it — so the chain is
#: complete, and re-checking the copies would only demand markers that the
#: generator deliberately removed.
GENERATED = {ROOT / "outreach" / "devto"}

SHELL_LANGS = {"bash", "sh", "shell", "console", "zsh"}

#: Placeholder filename in the docs -> fixture that stands in for it.
PLACEHOLDERS = {
    "app-cbom.json": "conflict-hybrid.json",
    "app-cbom.cdx.json": "conflict-hybrid.json",
    "your-cbom.json": "conflict-hybrid.json",
    "cbom.json": "conflict-hybrid.json",
    "normalized.json": "sbom-tools-normalized.json",
}

FENCE = re.compile(r"^(?P<ind>[ \t]*)```(?P<lang>[A-Za-z0-9_+-]*)(?P<info>[^`]*)$")
COMMENT = re.compile(r"<!--(?P<body>.*?)-->", re.S)

_pypi_cache: dict[str, str] = {}


class Block:
    def __init__(self, path: Path, line: int, lang: str, body: list[str], note: str):
        self.path, self.line, self.lang, self.body = path, line, lang, body
        self.note = " ".join(note.split())

    @property
    def where(self) -> str:
        try:
            shown = self.path.relative_to(ROOT)
        except ValueError:               # a scratch document under test
            shown = self.path
        return f"{shown}:{self.line}"

    def annotation(self, kind: str) -> str | None:
        """The reason attached to `<!-- kind: reason -->`, or "" for a bare tag."""
        m = re.match(rf"{kind}\s*:\s*(.*)$", self.note, re.S)
        if m:
            return m.group(1).strip()
        return "" if self.note.strip() == kind else None


def blocks(path: Path):
    lines = path.read_text().split("\n")
    i = 0
    while i < len(lines):
        m = FENCE.match(lines[i])
        if not m:
            i += 1
            continue
        start, body = i + 1, []
        j = i + 1
        while j < len(lines) and not re.match(r"^[ \t]*```\s*$", lines[j]):
            body.append(lines[j])
            j += 1
        # The annotation is the HTML comment ending on the line above the fence.
        note = ""
        k = i - 1
        if k >= 0 and lines[k].rstrip().endswith("-->"):
            while k >= 0 and "<!--" not in lines[k]:
                k -= 1
            if k >= 0:
                cm = COMMENT.search("\n".join(lines[k:i]))
                if cm:
                    note = cm.group("body")
        yield Block(path, start, m.group("lang").lower(), body, note)
        i = j + 1


def scratch() -> Path:
    """A directory where the docs' placeholder filenames are real CBOMs."""
    d = Path(tempfile.mkdtemp(prefix="cbomctl-docs-"))
    for name, fixture in PLACEHOLDERS.items():
        shutil.copy(FIXTURES / fixture, d / name)
    shutil.copy(ROOT / "cbomctl.yaml.example", d / "cbomctl.yaml")
    shutil.copy(ROOT / "cbomctl.yaml.example", d / "cbomctl.yaml.example")
    (d / "tests").symlink_to(ROOT / "tests")
    return d


def run_cbomctl(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "cbomctl.cli", *args],
        capture_output=True, text=True, cwd=cwd,
        env={**os.environ, "PYTHONPATH": str(SRC), "NO_COLOR": "1",
             "TERM": "dumb", "COLUMNS": "100"},
    )


def pypi_has(name: str) -> str:
    """PASS / FAIL / SKIP for `pip install <name>` resolving on the index."""
    if name in _pypi_cache:
        return _pypi_cache[name]
    url = f"https://pypi.org/pypi/{name}/json"
    try:
        with urllib.request.urlopen(url, timeout=10) as fh:
            json.load(fh)
        verdict = "PASS"
    except urllib.error.HTTPError as exc:
        verdict = "FAIL" if exc.code == 404 else "SKIP"
    except Exception:
        # A python.org build with no CA bundle cannot verify pypi.org, and that
        # is a fact about this laptop, not about the package. Ask curl before
        # reporting the claim unchecked.
        code = subprocess.run(
            ["curl", "-sS", "-o", os.devnull, "-w", "%{http_code}", "--max-time", "15", url],
            capture_output=True, text=True).stdout.strip()
        verdict = {"200": "PASS", "404": "FAIL"}.get(code, "SKIP")
    _pypi_cache[name] = verdict
    return verdict


def all_commands(body: list[str]) -> bool:
    """True for an untagged fence that is only commands, not a transcript.

    A block that opens `$ cbomctl verdict ...` and then shows the matrix is a
    transcript: its command half is not what needs checking, its output half
    is. Those go to `check_output` and must be generated.
    """
    lines = [l.strip() for l in body if l.strip()]
    return bool(lines) and all(
        l.lstrip("$ ").startswith("cbomctl ") or l.startswith("#") for l in lines)


def check_repo_local(line: str) -> tuple[str | None, str]:
    """Resolve commands that point at this repo, without running them.

    `./scripts/check.sh` invokes this file, so executing it here would recurse.
    What is checkable without running is whether the thing named exists — which
    is the failure mode that actually happens: a script renamed, an extra
    dropped from `pyproject.toml`, a path in a `cat` that moved.
    """
    m = re.match(r"^(?:\./)?(scripts/[\w.-]+)(?:\s.*)?$", line)
    if not m:
        m = re.match(r"^python3?\s+(scripts/[\w.-]+)(?:\s.*)?$", line)
    if m:
        target = ROOT / m.group(1)
        if not target.exists():
            return "FAIL", f"{m.group(1)} does not exist"
        if line.startswith("./") and not os.access(target, os.X_OK):
            return "FAIL", f"{m.group(1)} is not executable"
        return "CHECKED", f"{m.group(1)} exists"

    m = re.match(r"^pip3? install -e ['\"]?\.\[(\w+)\]['\"]?$", line)
    if m:
        extras = (ROOT / "pyproject.toml").read_text()
        block = extras.split("[project.optional-dependencies]", 1)
        if len(block) < 2 or not re.search(rf"^{m.group(1)}\s*=", block[1], re.M):
            return "FAIL", f"pyproject declares no `{m.group(1)}` extra"
        return "CHECKED", f"`{m.group(1)}` extra is declared in pyproject.toml"

    if re.match(r"^pytest(\s|$)", line):
        deps = (ROOT / "pyproject.toml").read_text()
        return ("CHECKED", "pytest is a declared test dependency") if "pytest" in deps \
            else ("FAIL", "pytest is not a declared dependency")

    m = re.match(r"^cat\s+([\w./-]+)$", line)
    if m:
        target = ROOT / m.group(1)
        return ("CHECKED", f"{m.group(1)} exists") if target.exists() \
            else ("FAIL", f"{m.group(1)} does not exist")

    return None, ""


def check_shell(b: Block, cwd: Path, report: list) -> bool:
    reason = b.annotation("unverified")
    if reason is not None:
        if not reason:
            report.append(("FAIL", b.where, "`unverified` with no reason given"))
            return False
        report.append(("SKIP", b.where, f"unverified — {reason}"))
        return True

    ok = True
    for raw in b.body:
        line = raw.strip().lstrip("$ ").strip()
        trailing = re.search(r"\s+#\s*(.*)$", line)
        line = re.sub(r"\s+#.*$", "", line)          # trailing prose comment
        if not line or line.startswith("#"):
            continue

        # One unrunnable line should not cost a block its other checks, so the
        # annotation is available per line as well: `cmd  # unverified: why`.
        if trailing and trailing.group(1).startswith("unverified:"):
            why = trailing.group(1)[len("unverified:"):].strip()
            if not why:
                report.append(("FAIL", b.where,
                               f"`{line}` — `unverified` with no reason given"))
                ok = False
            else:
                report.append(("SKIP", b.where, f"`{line}` — unverified: {why}"))
            continue

        if re.match(r"^(pip|pip3|python3? -m pip) install ([A-Za-z0-9._-]+)$", line):
            name = line.split()[-1]
            verdict = pypi_has(name)
            report.append((verdict, b.where,
                           f"`{line}` — {name} on PyPI"
                           if verdict != "SKIP" else
                           f"`{line}` — index unreachable, not verified"))
            ok &= verdict != "FAIL"
            continue

        if not line.startswith("cbomctl "):
            verdict, detail = check_repo_local(line)
            if verdict is None:
                report.append(("FAIL", b.where, (
                    f"`{line}` is not a cbomctl invocation and the block carries "
                    f"no `<!-- unverified: reason -->`")))
                ok = False
            else:
                report.append((verdict, b.where, f"`{line}` — {detail}"))
                ok &= verdict != "FAIL"
            continue

        if re.search(r"[|;&><`]|\$\(", line):
            report.append(("FAIL", b.where,
                           f"`{line}` uses shell plumbing; run it or annotate it"))
            ok = False
            continue

        proc = run_cbomctl(shlex.split(line)[1:], cwd)
        blew_up = proc.returncode == 2 or "No such command" in proc.stderr
        report.append(("FAIL" if blew_up else "RAN", b.where,
                       f"`{line}` → exit {proc.returncode}"
                       + (f"\n        {proc.stderr.strip().splitlines()[0]}"
                          if blew_up and proc.stderr.strip() else "")))
        ok &= not blew_up
    return ok


def check_synopsis(b: Block, cwd: Path, report: list) -> bool:
    """A usage sketch is not runnable, but its flags must be real."""
    ok = True
    for raw in b.body:
        line = raw.strip()
        if not line:
            continue
        sub = None
        if line.startswith("cbomctl "):
            rest = line[len("cbomctl "):].split()
            sub = rest[0] if rest and not rest[0].startswith("-") else None
        if sub:
            proc = run_cbomctl([sub, "--help"], cwd)
            if proc.returncode != 0:
                report.append(("FAIL", b.where, f"no such subcommand: `{sub}`"))
                ok = False
                continue
            b._help = proc.stdout                                # noqa: SLF001
        help_text = getattr(b, "_help", "")
        for flag in re.findall(r"(?<![\w-])--[a-z][a-z0-9-]*", line):
            if help_text and flag not in help_text:
                report.append(("FAIL", b.where,
                               f"`{flag}` is not a flag the CLI has"))
                ok = False
    if ok:
        report.append(("CHECKED", b.where, "synopsis — subcommands and flags exist"))
    return ok


def check_output(b: Block, cwd: Path, report: list) -> bool:
    """An untagged fence in prose has to say what it is.

    Heuristics were tried first — look for `└ `, for `CONFLICTS (`, for a
    matrix header — and every one of them missed something. The fiction on the
    docs-site landing page had a bare `CONFLICTS` with no count; the block in
    `purpose.md` was a paraphrase with no tell at all. A fence either declares
    itself or it fails; there are few enough of them for that to be cheap.
    """
    if b.annotation("cbomctl") is not None:
        return True                       # gen_article_blocks.py owns this one

    cmd = b.annotation("excerpt")
    if cmd is not None:
        # Prose that quotes a few lines of output, rewrapped to the narrower
        # column the prose uses. `illustrative` would excuse it; this pins it
        # to the command instead, and checks against that command's *whole*
        # output — the quote is often a line the pasted block truncates away.
        if not cmd:
            report.append(("FAIL", b.where,
                           "`excerpt` needs the command it quotes: "
                           "`<!-- excerpt: verdict ... -->`"))
            return False
        args = shlex.split(cmd)
        proc = run_cbomctl(args[1:] if args[:1] == ["cbomctl"] else args, cwd)
        quoted = " ".join(" ".join(b.body).split())
        if quoted and quoted in " ".join(proc.stdout.split()):
            report.append(("CHECKED", b.where,
                           f"excerpt — found verbatim in `cbomctl {cmd}` output"))
            return True
        report.append(("FAIL", b.where, (
            f"marked `excerpt` of `cbomctl {cmd}`, but that command's output "
            f"does not contain it")))
        return False

    for kind in ("illustrative", "unverified"):
        reason = b.annotation(kind)
        if reason:
            report.append(("SKIP", b.where, f"{kind} — {reason}"))
            return True
        if reason == "":
            report.append(("FAIL", b.where, f"`{kind}` with no reason given"))
            return False
    report.append(("FAIL", b.where, (
        "untagged fence — if it is tool output give it a `<!-- cbomctl: ... -->` "
        "marker so it is generated; if it is a usage sketch mark it "
        "`<!-- synopsis -->`; otherwise `<!-- illustrative: reason -->`")))
    return False


def check_workflow(b: Block, report: list) -> bool:
    """A CI snippet that names our action must name inputs the action has."""
    text = "\n".join(b.body)
    if "lvlrSajjad/cbomctl@" not in text:
        return True

    action = (ROOT / "action.yml").read_text()
    inputs_block = action.split("\ninputs:", 1)[1].split("\noutputs:", 1)[0]
    declared = set(re.findall(r"^  ([\w-]+):$", inputs_block, re.M))

    ok = True
    ref = re.search(r"lvlrSajjad/cbomctl@(\S+)", text).group(1)
    known = subprocess.run(["git", "tag"], capture_output=True, text=True,
                           cwd=ROOT).stdout.split()
    if not known:
        # A shallow checkout has no tags. Saying nothing here would let the
        # check pass by accident, which is the failure this file exists to stop.
        report.append(("SKIP", b.where,
                       f"`@{ref}` unresolved — no tags in this checkout "
                       f"(fetch-depth: 0 is needed to verify it)"))
    elif ref not in known:
        report.append(("FAIL", b.where, f"`@{ref}` is not a tag in this repo"))
        ok = False

    used = with_keys(b.body, f"lvlrSajjad/cbomctl@{ref}")
    for key in used:
        if key not in declared:
            report.append(("FAIL", b.where, f"`with: {key}` is not an action input"))
            ok = False
    if ok:
        report.append(("CHECKED", b.where,
                       f"action `@{ref}` exists; inputs {sorted(used)} declared"))
    return ok


def with_keys(body: list[str], uses: str) -> list[str]:
    """Keys of the `with:` mapping on the step that `uses` the given action."""
    keys: list[str] = []
    step_indent = None
    for i, line in enumerate(body):
        if uses not in line:
            continue
        step_indent = len(line) - len(line.lstrip())
        for rest in body[i + 1:]:
            if not rest.strip():
                continue
            indent = len(rest) - len(rest.lstrip())
            if indent <= step_indent and rest.lstrip().startswith("- "):
                break                                   # next step
            m = re.match(r"^\s*with:\s*\{(.*)\}\s*$", rest)
            if m:                                       # inline `with: { a: b }`
                keys += re.findall(r"([\w-]+)\s*:", m.group(1))
                continue
            if re.match(r"^\s*with:\s*$", rest):
                continue
            if indent > step_indent + 2:
                m = re.match(r"^\s*([\w-]+):", rest)
                if m:
                    keys.append(m.group(1))
        break
    return sorted(set(keys))


def main() -> int:
    check = "--check" in sys.argv
    cwd = scratch()
    report: list[tuple[str, str, str]] = []
    ok = True
    try:
        paths: list[Path] = []
        for base in SEARCH:
            paths += [base] if base.is_file() else sorted(base.rglob("*.md"))
        for path in paths:
            if any(g in path.parents for g in GENERATED):
                continue
            for b in blocks(path):
                if b.annotation("synopsis") is not None:
                    ok &= check_synopsis(b, cwd, report)
                elif b.lang in SHELL_LANGS or (not b.lang and all_commands(b.body)):
                    ok &= check_shell(b, cwd, report)
                elif b.lang in ("", "text"):
                    ok &= check_output(b, cwd, report)
                elif b.lang in ("yaml", "yml"):
                    ok &= check_workflow(b, report)
                elif b.annotation("unverified") is not None:
                    reason = b.annotation("unverified")
                    if not reason:
                        report.append(("FAIL", b.where,
                                       "`unverified` with no reason given"))
                        ok = False
                    else:
                        report.append(("SKIP", b.where, f"unverified — {reason}"))
    finally:
        shutil.rmtree(cwd, ignore_errors=True)

    width = max((len(w) for _, w, _ in report), default=0)
    for verdict, where, detail in report:
        print(f"  {verdict:<8} {where:<{width}}  {detail}")

    tally = {v: sum(1 for x, _, _ in report if x == v) for v in
             ("RAN", "PASS", "CHECKED", "SKIP", "FAIL")}
    print(f"\n  {tally['RAN']} commands executed, {tally['PASS']} resolved on PyPI, "
          f"{tally['CHECKED']} statically checked, {tally['SKIP']} marked unverified, "
          f"{tally['FAIL']} failing")
    if not ok:
        print("\nA command presented as working must have been run. If it cannot "
              "be run here,\nsay so above the fence: <!-- unverified: reason -->")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
